### ISSUE TITLE
finished the requirements with File Sink and Permutations

### ISSUE THREAD

**Issue by florian4300** [htl-perg-2019-20-5ahif/anagram-checker-exercise-florian4300#1]
Hey @rstropek !

I did all the requirements with the bonus exercises. 
I hope I did the logging as requested. I saved the log to the "log.txt".

**Comment by rstropek** [comment]
Nice 👍, the extra points are yours.

Just to make sure: No need to write every API controller method in a separate file. I did that in my sample because I need separate files for the online slides. In practice, it is ok to put multiple controller methods in a single C# file.

Greetings,
Rainer Stropek.
